#!/bin/bash


# $1 : CMSSW version
if [ "$1" = "" ] 
then
    echo " Need a CMSSW version. exit."
    echo " Syntax : cmsRun_batch_eos CMSSWDIR configfile.cfg (INPUTFILE)"
    exit
fi

# CMSSW directory
CMSSWDIR=$1

#starting directory
echo "You are working here : "
pwd
echo "Your CMSSW directory is :"
echo $CMSSWDIR
echo

cd $CMSSWDIR
eval `scramv1 runtime -sh`
cd -

# $2 : config file
if [ "$2" != "" ] 
  then
    echo "cp $2 ."
    cp $2 .
  else
    echo " Need a configuration file. exit."
    echo " Syntax : cmsRun_batch_eos CMSSWDIR configfile.cfg (INPUTFILE)(NOFJOBS)(NOFFILESPERJOB)"
    exit
fi
configfile=`echo $2 | awk -F/ '{print $NF}' | awk -F. '{print $1}'`

cat ${configfile}.py > ${configfile}_temp.py

# copy input file
if [ "$3" != "" ] ; then
    echo "cp $CMSSWDIR/$3 ."
    cp $CMSSWDIR/$3 .
fi

# copy bad modules file
BADMODULEFILE=$CMSSWDIR/BadModules_input.txt
if [ -f "$BADMODULEFILE" ]; then
        echo "cp $CMSSWDIR/BadModules_input.txt ."
        cp $CMSSWDIR/BadModules_input.txt .
fi

# $4 : job number 
JOBNUMBER=1
if [ "$4" != "" ] ; then
    JOBNUMBER=$4
fi

# $5 : number of files per job
NOFFILESPERJOB=1
if [ "$5" != "" ] ; then
    NOFFILESPERJOB=$5
fi

sed -i "s/.root/_${JOBNUMBER}.root/g" ${configfile}_temp.py

echo "cmsRun ${configfile}_temp.py FileList=$3 JobNumber=$JOBNUMBER NofFilesPerJob=$NOFFILESPERJOB"
cmsRun ${configfile}_temp.py FileList=$3 JobNumber=$JOBNUMBER NofFilesPerJob=$NOFFILESPERJOB

echo
ls -lhrt
echo

echo ""

exit
